#+title: Emacs Config
#+TODO: DISABLED

* Package Management

** Use Package

Install packages by default when configured with use-package.

#+begin_src emacs-lisp
(setq use-package-always-ensure t)
#+end_src

Macro to use to configure built-in features, rather than packages that do not
need to be installed.

#+begin_src emacs-lisp
(defmacro use-feature (name &rest args)
  "`use-package' with package installation (`ensure') disabled."
  (declare (indent defun))
  `(use-package ,name
     :ensure nil
     ,@args))
#+end_src

* Base Settings

** Customization Saving

Do not save customizations in =init.el=; Instead save them in a temporary file that will be discarded. As a result, any customizations made in a session will not be persisted across sessions.

#+begin_src emacs-lisp
(setq custom-file (expand-file-name
                   (format "custom-%d-%d.el" (emacs-pid) (random))
                   temporary-file-directory))
#+end_src

** No Littering

Move all common files typically written to the =user-emacs-directory= to the =var= and =etc= subdirectories so that they can be included in =.gitignore=.

#+begin_src emacs-lisp
(use-package no-littering
  :ensure (:wait t))
#+end_src

** Minibuffer

Support opening new minibuffers from inside existing minibuffers.

#+begin_src emacs-lisp
(setq enable-recursive-minibuffers t)
#+end_src

Do not allow the cursor in the minibuffer prompt.

#+begin_src emacs-lisp
(setq minibuffer-prompt-properties
      '(read-only t cursor-intangible t face minibuffer-prompt))

(add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)
#+end_src

** Don't allow org to change indentation

Org mode indents elsip weird. Prevent that.

#+begin_src emacs-lisp
(setq org-adapt-indentation nil)
#+end_src

** Show Line Numbers

Show line numbers when in a programming mode.

#+begin_src emacs-lisp
(add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+end_src


#+begin_src emacs-lisp
#+end_src

* Magit
* User Interface

** Completion Menu (Vertico)

#+begin_src emacs-lisp
(use-package vertico
  :init
  (vertico-mode))
#+end_src

** Consult

#+begin_src emacs-lisp
(use-package consult
  :bind (("C-x b" . consult-buffer)))
#+end_src

** Completion Style (Orderless)

The orderless completion style allows typing parts of what is being matched,
separated by spaces. For example, "som thi" will match "this-is-some-thing".

#+begin_src emacs-lisp
(use-package orderless
  :init
  (setq completion-styles '(orderless basic)
        completion-category-defaults nil
        completion-category-overrides '((file (styles partial-completion)))))
#+end_src

One half of the reason I used emacs

** Transient

The current base =magit= package (as of Thu Nov 7 2024) requires a higher version of =transient= than what gets installed with =magit=. Force a higher verison.

#+begin_src emacs-lisp
(use-package transient
  :ensure (:tag "v0.7.9" :wait t))
#+end_src

** Magit

#+begin_src emacs-lisp
(use-package magit
  :ensure (:wait t))
#+end_src

* Markdown Mode

I write Markdown files

#+begin_src emacs-lisp
(use-package markdown-mode
  :ensure (markdown-mode :host github :repo "jrblevin/markdown-mode" :protocol ssh :wait t)
  :init (setq markdown-command "multimarkdown"))
#+end_src

* Strip Whitespace

#+begin_src emacs-lisp
  (use-package ws-butler
    :ensure (ws-butler :host github :repo "hlissner/ws-butler" :protocol ssh :wait t)
    :config
    (setq ws-butler-keep-whitespace-before-point nil)
    ;; Do not exempt markdown mode
    (delq 'markdown-mode ws-butler-global-exempt-modes))

  (ws-butler-global-mode)
#+end_src

* Startup Time

#+begin_src emacs-lisp
(add-hook 'after-init-hook
          (lambda ()
            (let ((inhibit-message t))
              (message "Emacs init time: %s" (emacs-init-time)))))
#+end_src
